// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqBPFuwjHOcgah0DTCa7FLVtDJlZEWEvY',
    appId: '1:597148037834:web:a3b74577530548999fba33',
    messagingSenderId: '597148037834',
    projectId: 'commerce-cce36',
    authDomain: 'commerce-cce36.firebaseapp.com',
    storageBucket: 'commerce-cce36.firebasestorage.app',
    measurementId: 'G-4JCEQ0XHPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8ANQ2SRvoVWwXjUh9gWyiE4R3ZAgvSg',
    appId: '1:597148037834:android:f43886b15bad34b89fba33',
    messagingSenderId: '597148037834',
    projectId: 'commerce-cce36',
    storageBucket: 'commerce-cce36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYvcoA5IcgUF-aVxIZhKYlaF4ACzihBs',
    appId: '1:597148037834:ios:0e1a6253ff73a7679fba33',
    messagingSenderId: '597148037834',
    projectId: 'commerce-cce36',
    storageBucket: 'commerce-cce36.firebasestorage.app',
    iosClientId:
        '597148037834-07cmo4hhdm7hplkka3bvci5sb1ild07m.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerce8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtYvcoA5IcgUF-aVxIZhKYlaF4ACzihBs',
    appId: '1:597148037834:ios:0e1a6253ff73a7679fba33',
    messagingSenderId: '597148037834',
    projectId: 'commerce-cce36',
    storageBucket: 'commerce-cce36.firebasestorage.app',
    iosClientId:
        '597148037834-07cmo4hhdm7hplkka3bvci5sb1ild07m.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerce8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqBPFuwjHOcgah0DTCa7FLVtDJlZEWEvY',
    appId: '1:597148037834:web:576a3be78a1d52cb9fba33',
    messagingSenderId: '597148037834',
    projectId: 'commerce-cce36',
    authDomain: 'commerce-cce36.firebaseapp.com',
    storageBucket: 'commerce-cce36.firebasestorage.app',
    measurementId: 'G-6NXTVDQFX4',
  );
}
